/* Sticker Reward System - Universal Game Integration. Usage: StickerReward.award(count, gameName) */
const StickerReward=(()=>{
const GK='sticker-album-global';
const AL=['purim','pesach','heroes','relaxation','military','gooddeeds'];
const ST={
purim:[{id:'p1',name:'המלכה קוראת במגילה'},{id:'p2',name:'הצדיק מתפלל'},{id:'p3',name:'ילדים בתחפושות'},{id:'p4',name:'שולחן עם מאכלים'},{id:'p5',name:'נגנים מנגנים'},{id:'p6',name:'מתנות לאביונים'},{id:'p7',name:'משפחה קוראת'},{id:'p8',name:'ילדים עם רעשנים'},{id:'p9',name:'תהלוכה חגיגית'}],
pesach:[{id:'s1',name:'מעבר בים'},{id:'s2',name:'נושאי המצות'},{id:'s3',name:'ליל הסדר'},{id:'s4',name:'ילדים שואלים'},{id:'s5',name:'המנהיג עם המטה'},{id:'s6',name:'שירה ותופים'},{id:'s7',name:'בונים במדבר'},{id:'s8',name:'חיפוש חמץ'},{id:'s9',name:'זריחת החירות'}],
heroes:[{id:'h1',name:'שמירה על הגבול'},{id:'h2',name:'חובשים מצילים'},{id:'h3',name:'מתנדבים אורזים'},{id:'h4',name:'סרטים צהובים'},{id:'h5',name:'מורה עם תלמידים'},{id:'h6',name:'כבאים מצילים'},{id:'h7',name:'מארחים מפונים'},{id:'h8',name:'נרות זיכרון'},{id:'h9',name:'חיבוק על הגבעה'}],
relaxation:[{id:'r1',name:'מדיטציה ליד מפל'},{id:'r2',name:'יוגה על ההר'},{id:'r3',name:'קריאה תחת עץ'},{id:'r4',name:'ציור בטבע'},{id:'r5',name:'פיקניק שקט'},{id:'r6',name:'נגינה רגועה'},{id:'r7',name:'גינון עם פרחים'},{id:'r8',name:'שחייה באגם'},{id:'r9',name:'צפייה בכוכבים'}],
military:[{id:'m1',name:'אימון ביחד'},{id:'m2',name:'תצפית מהגבעה'},{id:'m3',name:'שבת בבסיס'},{id:'m4',name:'מכתב מהבית'},{id:'m5',name:'טקס כומתות'},{id:'m6',name:'עזרה לקהילה'},{id:'m7',name:'סיור בנוף'},{id:'m8',name:'מדורה עם חברים'},{id:'m9',name:'שתילת עצים'}],
gooddeeds:[{id:'g1',name:'עזרה לקשיש'},{id:'g2',name:'חבילות לחיילים'},{id:'g3',name:'ביקור חולים'},{id:'g4',name:'תרומת בגדים'},{id:'g5',name:'עזרה בשיעורים'},{id:'g6',name:'ניקוי חוף'},{id:'g7',name:'שתילה בפארק'},{id:'g8',name:'בישול לנזקקים'},{id:'g9',name:'חיבוק קהילתי'}]};
const FB='https://album-bea15-default-rtdb.firebaseio.com';
const AN={purim:'פורים',pesach:'פסח',heroes:'גיבורים',relaxation:'הרגעות',military:'צבאי',gooddeeds:'מעשים טובים'};
function sk(c){return'space-'+c}
function lg(){try{var r=localStorage.getItem(GK);if(r)return JSON.parse(r)}catch(e){}return null}
function ls(c){try{var r=localStorage.getItem(sk(c));if(r)return JSON.parse(r)}catch(e){}return null}
function ss(c,s){localStorage.setItem(sk(c),JSON.stringify(s))}
function esc(s){var d=document.createElement('div');d.textContent=s;return d.innerHTML}
function pr(state){var ap=AL.flatMap(function(a){return ST[a].map(function(s){return{id:s.id,theme:a,name:s.name}})});var cl=new Set(AL.flatMap(function(a){return(state.collected&&state.collected[a])||[]}));var uc=ap.filter(function(p){return!cl.has(p.id)});var pick;if(uc.length===0||(cl.size>5&&Math.random()<0.3&&cl.size<54)){var ca=ap.filter(function(p){return cl.has(p.id)});if(ca.length===0)return null;pick=ca[Math.floor(Math.random()*ca.length)];pick._duplicate=true}else{pick=uc[Math.floor(Math.random()*uc.length)]}return pick||null}
function cs(state){if(!state.student||!state.student.joinCode)return;var mb=state.admin&&state.admin.members?state.admin.members.find(function(m){return m.name===state.student.name}):null;if(!mb)return;if(!mb.collected)mb.collected={};for(var t in state.collected){if(!mb.collected[t])mb.collected[t]=[];(state.collected[t]||[]).forEach(function(id){if(!mb.collected[t].includes(id))mb.collected[t].push(id)})}if(!mb.stickers)mb.stickers=[];Object.values(state.collected).flat().forEach(function(id){if(!mb.stickers.includes(id))mb.stickers.push(id)});var url=FB+'/spaces/'+state.student.joinCode+'/studentSync/'+encodeURIComponent(mb.name)+'.json';try{fetch(url,{method:'PUT',keepalive:true,headers:{'Content-Type':'application/json'},body:JSON.stringify(mb)})}catch(e){}}
function ic(){if(document.getElementById('sr-css'))return;var s=document.createElement('style');s.id='sr-css';s.textContent='#sr-overlay{position:fixed;inset:0;background:rgba(0,0,0,.75);z-index:99999;display:flex;align-items:center;justify-content:center;padding:16px;backdrop-filter:blur(6px);opacity:0;transition:opacity .3s}#sr-overlay.show{opacity:1}#sr-box{background:linear-gradient(135deg,#1e1b4b,#0f172a);border:3px solid #f59e0b;border-radius:24px;padding:28px 24px;max-width:420px;width:100%;text-align:center;direction:rtl;font-family:Heebo,sans-serif;color:#f1f5f9;box-shadow:0 25px 80px rgba(0,0,0,.8),0 0 60px rgba(245,158,11,.2);transform:scale(.8);transition:transform .35s cubic-bezier(.34,1.56,.64,1)}#sr-overlay.show #sr-box{transform:scale(1)}#sr-title{font-size:28px;font-weight:900;margin-bottom:4px;background:linear-gradient(90deg,#f59e0b,#fbbf24);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}#sr-sub{font-size:15px;color:#94a3b8;margin-bottom:16px}.sr-s{display:inline-flex;align-items:center;gap:8px;background:rgba(245,158,11,.15);border:2px solid rgba(245,158,11,.4);border-radius:14px;padding:10px 16px;margin:5px;font-size:15px;font-weight:700;color:#fde68a;animation:srP .4s ease both}.sr-s.sr-d{border-color:rgba(148,163,184,.3);background:rgba(255,255,255,.05);color:#94a3b8}@keyframes srP{0%{transform:scale(0) rotate(-15deg);opacity:0}60%{transform:scale(1.15) rotate(3deg)}100%{transform:scale(1) rotate(0);opacity:1}}#sr-total{font-size:14px;color:#a78bfa;margin-top:14px}#sr-btn{display:inline-block;margin-top:16px;padding:12px 32px;background:linear-gradient(135deg,#f59e0b,#d97706);color:#1e293b;border:none;border-radius:14px;font-family:Heebo;font-weight:900;font-size:17px;cursor:pointer;transition:transform .2s}#sr-btn:hover{transform:scale(1.05)}#sr-al{display:inline-block;margin-top:10px;color:#fbbf24;font-size:14px;font-weight:700;text-decoration:none}@keyframes srC{0%{transform:translateY(0) rotate(0);opacity:1}100%{transform:translateY(120vh) rotate(720deg);opacity:0}}.sr-c{position:fixed;top:-20px;width:10px;height:10px;border-radius:2px;z-index:100000;pointer-events:none;animation:srC 2.5s ease-out forwards}';document.head.appendChild(s)}
function cf(){var co=['#f59e0b','#a855f7','#3b82f6','#10b981','#ef4444','#ec4899','#fbbf24'];for(var i=0;i<40;i++){var c=document.createElement('div');c.className='sr-c';c.style.left=Math.random()*100+'vw';c.style.background=co[Math.floor(Math.random()*co.length)];c.style.width=(6+Math.random()*8)+'px';c.style.height=(6+Math.random()*8)+'px';c.style.animationDelay=(Math.random()*0.8)+'s';c.style.animationDuration=(1.5+Math.random()*1.5)+'s';document.body.appendChild(c);setTimeout(function(el){return function(){el.remove()}}(c),3500)}}
function ps(){try{var ctx=new(window.AudioContext||window.webkitAudioContext)();[523,659,784,1047,1319].forEach(function(f,i){var o=ctx.createOscillator(),g=ctx.createGain();o.connect(g);g.connect(ctx.destination);o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(0.25,ctx.currentTime+i*0.12);g.gain.exponentialRampToValueAtTime(0.001,ctx.currentTime+i*0.12+0.2);o.start(ctx.currentTime+i*0.12);o.stop(ctx.currentTime+i*0.12+0.21)})}catch(e){}}
function gp(){var iS=window.location.pathname.includes('/stations/');var iG=window.location.pathname.includes('/games/');return iS?'../../sticker-album/':(iG?'../sticker-album/':'sticker-album/')}
function sp(aw,gn,tc){ic();var old=document.getElementById('sr-overlay');if(old)old.remove();var ov=document.createElement('div');ov.id='sr-overlay';var h=aw.map(function(s,i){var d=s._duplicate?' sr-d':'';var dl=s._duplicate?' (כפול — להחלפה!)':'';var an=AN[s.theme]||s.theme;return'<div class="sr-s'+d+'" style="animation-delay:'+(i*0.15)+'s">🧩 '+esc(s.name)+' <small>('+esc(an)+')'+dl+'</small></div>'}).join('');ov.innerHTML='<div id="sr-box"><div id="sr-title">🎁 קיבלת מדבקות!</div><div id="sr-sub">כל הכבוד על '+esc(gn)+'!</div><div>'+h+'</div><div id="sr-total">🏅 סה"כ באלבום: '+tc+' / 54</div><button id="sr-btn" onclick="this.closest(\'#sr-overlay\').remove()">יאללה! 🎉</button><br><a id="sr-al" href="'+gp()+'">📖 לאלבום המדבקות →</a></div>';document.body.appendChild(ov);requestAnimationFrame(function(){ov.classList.add('show')});cf();ps()}
function snl(gn){ic();var old=document.getElementById('sr-overlay');if(old)old.remove();var ov=document.createElement('div');ov.id='sr-overlay';ov.innerHTML='<div id="sr-box"><div id="sr-title">🎁 הרווחת מדבקות!</div><div id="sr-sub">כל הכבוד על '+esc(gn)+'!</div><div style="font-size:15px;color:#fde68a;margin:16px 0;line-height:1.8">כדי לקבל את המדבקות,<br>היכנסו לאלבום המדבקות והתחברו עם קוד הכיתה 🔑</div><a id="sr-btn" href="'+gp()+'" style="text-decoration:none;display:inline-block">📖 לאלבום המדבקות</a></div>';document.body.appendChild(ov);requestAnimationFrame(function(){ov.classList.add('show')});ps()}
function award(count,gameName){count=Math.max(1,Math.min(5,count||1));var gl=lg();if(!gl||!gl.activeSpace){snl(gameName);return null}var state=ls(gl.activeSpace);if(!state||!state.student){snl(gameName);return null}if(!state.collected)state.collected={purim:[],pesach:[],heroes:[],relaxation:[],military:[],gooddeeds:[]};AL.forEach(function(a){if(!state.collected[a])state.collected[a]=[]});var aw=[];for(var i=0;i<count;i++){var pick=pr(state);if(!pick)break;var mb=state.admin&&state.admin.members?state.admin.members.find(function(m){return m.name===state.student.name}):null;if(mb){if(!mb.stickers)mb.stickers=[];mb.stickers.push(pick.id);if(pick._duplicate){if(!mb.duplicates)mb.duplicates=[];mb.duplicates.push(pick.id)}}if(!pick._duplicate){state.collected[pick.theme].push(pick.id)}state.points=(state.points||0)+5;aw.push(pick)}if(aw.length>0){ss(gl.activeSpace,state);cs(state);var tc=AL.reduce(function(s,a){return s+(state.collected[a]?state.collected[a].length:0)},0);sp(aw,gameName,tc)}return{awarded:aw.length,stickers:aw}}
return{award:award}})();
